export const weeklyGoalsMock = [
  {
    id: 1,
    title: "Complete 3 Python Modules",
    type: "Course",
    current: 3,
    total: 3,
    achieved: true,
    achievedDay: "Monday",
    dueDay: "Monday",
  },
  {
    id: 2,
    title: "Solve 10 Logic Puzzles",
    type: "Practice",
    current: 10,
    total: 10,
    achieved: true,
    achievedDay: "Wednesday",
    dueDay: "Wednesday",
  },
  {
    id: 3,
    title: "Daily Streak 15/20 Days",
    type: "Streak",
    current: 15,
    total: 20,
    achieved: false,
    achievedDay: null,
    dueDay: "Sunday",
  },
  {
    id: 4,
    title: "Pass Mock Certification",
    type: "Exam",
    current: 0,
    total: 1,
    achieved: false,
    achievedDay: null,
    dueDay: "Friday",
  },
];
