export const expiringPlansMock = [
  {
    id: 1,
    title: "Advanced React Patterns - Module 4",
    courseName: "Advanced React Patterns",
    dueDate: "2026-05-18",
    daysLeft: 1,
    priority: "High",
    status: "Due Soon",
    description:
      "Module 4 is close to its deadline and still needs the final pattern review and practice checkpoint.",
    progress: 78,
    estimatedTime: "45 min",
    owner: "React Learning Track",
    lastUpdated: "2026-05-17",
    nextSteps: [
      "Review render props and compound component examples.",
      "Complete the module quiz before the deadline.",
      "Mark the checkpoint as finished after submitting your answers.",
    ],
  },
  {
    id: 2,
    title: "Machine Learning Quiz Review",
    courseName: "Machine Learning Certification",
    dueDate: "2026-05-19",
    daysLeft: 2,
    priority: "Medium",
    status: "Pending",
    description:
      "Your certification quiz review is pending. Focus on weak areas before attempting the assessment.",
    progress: 64,
    estimatedTime: "1h 15m",
    owner: "AI Certification Path",
    lastUpdated: "2026-05-17",
    nextSteps: [
      "Revisit model evaluation notes.",
      "Practice five quiz questions from the review set.",
      "Check the certification progress after finishing the review.",
    ],
  },
  {
    id: 3,
    title: "UI/UX Case Study Draft",
    courseName: "UI/UX Design Fundamentals",
    dueDate: "2026-05-20",
    daysLeft: 3,
    priority: "Low",
    status: "Scheduled",
    description:
      "The draft is scheduled for submission soon. Add project context, design decisions, and final screenshots.",
    progress: 52,
    estimatedTime: "1h",
    owner: "Design Fundamentals Track",
    lastUpdated: "2026-05-16",
    nextSteps: [
      "Write the problem statement and target user summary.",
      "Add wireframe and final UI screenshots.",
      "Proofread the conclusion before submitting.",
    ],
  },
  {
    id: 4,
    title: "Frontend Performance Audit",
    courseName: "Frontend Performance",
    dueDate: "2026-05-21",
    daysLeft: 4,
    priority: "Medium",
    status: "In Review",
    description:
      "The performance audit needs final Lighthouse notes and a short optimization summary before submission.",
    progress: 70,
    estimatedTime: "50 min",
    owner: "Web Development Track",
    lastUpdated: "2026-05-18",
    nextSteps: [
      "Run one final Lighthouse report.",
      "Document the largest contentful paint improvement.",
      "Submit the before-and-after performance notes.",
    ],
  },
  {
    id: 5,
    title: "Database Schema Exercise",
    courseName: "Database Design Basics",
    dueDate: "2026-05-22",
    daysLeft: 5,
    priority: "High",
    status: "Action Needed",
    description:
      "The schema exercise is missing relationship notes and normalization decisions for the final review.",
    progress: 46,
    estimatedTime: "1h 30m",
    owner: "Data Science Track",
    lastUpdated: "2026-05-18",
    nextSteps: [
      "Define primary and foreign key relationships.",
      "Add notes for first, second, and third normal form.",
      "Upload the completed entity relationship diagram.",
    ],
  },
  {
    id: 6,
    title: "React State Management Lab",
    courseName: "React State Management",
    dueDate: "2026-05-23",
    daysLeft: 6,
    priority: "Medium",
    status: "Pending",
    description:
      "The state management lab is waiting for reducer cleanup and a short reflection on state tradeoffs.",
    progress: 58,
    estimatedTime: "1h",
    owner: "React Learning Track",
    lastUpdated: "2026-05-19",
    nextSteps: [
      "Refactor duplicated reducer actions.",
      "Test the completed and pending task states.",
      "Write a short comparison between local and shared state.",
    ],
  },
  {
    id: 7,
    title: "Python Automation Checkpoint",
    courseName: "Python Automation Lab",
    dueDate: "2026-05-24",
    daysLeft: 7,
    priority: "Low",
    status: "Scheduled",
    description:
      "The automation checkpoint is scheduled for next week and includes a script review plus a small debugging task.",
    progress: 35,
    estimatedTime: "40 min",
    owner: "Python Learning Track",
    lastUpdated: "2026-05-19",
    nextSteps: [
      "Review file handling examples.",
      "Run the automation script with the sample dataset.",
      "Fix any failing validation messages.",
    ],
  },
  {
    id: 8,
    title: "UX Research Interview Notes",
    courseName: "UX Research Methods",
    dueDate: "2026-05-25",
    daysLeft: 8,
    priority: "Low",
    status: "Draft",
    description:
      "Interview notes need synthesis before they can be attached to the final UX research deliverable.",
    progress: 62,
    estimatedTime: "55 min",
    owner: "Design Fundamentals Track",
    lastUpdated: "2026-05-20",
    nextSteps: [
      "Group observations into three core themes.",
      "Highlight direct user pain points.",
      "Add a concise insight summary to the draft.",
    ],
  },
];

export const notificationsMock = {
  expiringPlans: expiringPlansMock,
};
