import gameIcon from "../../assets/icons/game-button.png";
import devIcon from "../../assets/icons/development.png";
import designIcon from "../../assets/icons/design.png";
import dataIcon from "../../assets/icons/datascience.png";
import goalImg from "../../assets/icons/goal.png";
import reactImg from "../../assets/images/react-course.png";
import pythonImg from "../../assets/images/python-course.png";
import uiuxImg from "../../assets/images/uiux-course.png";

export const coursesMock = [
  {
    id: 1,
    courseId: "CRS-1001",
    title: "Web Development Masterclass",
    instructor: "Sarah Johnson",
    rating: "★ 4.9",
    reviews: "(1.2k reviews)",
    status: "IN PROGRESS",
    progress: 60,
    learnedSections: 12,
    totalSections: 20,
    image: reactImg,
    actionIcon: gameIcon,
  },
  {
    id: 2,
    courseId: "CRS-1002",
    title: "Advanced React Patterns",
    instructor: "Michael Chen",
    rating: "★ 4.8",
    reviews: "(3.5k reviews)",
    status: "IN PROGRESS",
    progress: 35,
    learnedSections: 7,
    totalSections: 20,
    image: pythonImg,
    actionIcon: gameIcon,
    progressClass: "second",
  },
  {
    id: 3,
    courseId: "CRS-1003",
    title: "UI/UX Design Fundamentals",
    instructor: "Emily Carter",
    rating: "★ 5.0",
    reviews: "(850 reviews)",
    status: "COMPLETED",
    progress: 100,
    learnedSections: 18,
    totalSections: 18,
    image: uiuxImg,
    actionIcon: gameIcon,
    badgeClass: "completed",
    progressClass: "third",
  },
  {
    id: 4,
    courseId: "CRS-1004",
    title: "Python Data Essentials",
    instructor: "Maya Chen",
    rating: "★ 4.7",
    reviews: "(980 reviews)",
    status: "IN PROGRESS",
    progress: 48,
    learnedSections: 11,
    totalSections: 23,
    image: pythonImg,
    actionIcon: gameIcon,
  },
  {
    id: 5,
    courseId: "CRS-1005",
    title: "Product Design Systems",
    instructor: "Nina Patel",
    rating: "★ 4.9",
    reviews: "(720 reviews)",
    status: "COMPLETED",
    progress: 100,
    learnedSections: 16,
    totalSections: 16,
    image: uiuxImg,
    actionIcon: gameIcon,
    badgeClass: "completed",
    progressClass: "third",
  },
  {
    id: 6,
    courseId: "CRS-1006",
    title: "Frontend Performance",
    instructor: "Daniel Park",
    rating: "★ 4.6",
    reviews: "(1.1k reviews)",
    status: "IN PROGRESS",
    progress: 72,
    learnedSections: 13,
    totalSections: 18,
    image: reactImg,
    actionIcon: gameIcon,
  },
  {
    id: 7,
    courseId: "CRS-1007",
    title: "Node.js API Development",
    instructor: "Chris Morgan",
    rating: "鈽?4.8",
    reviews: "(1.6k reviews)",
    status: "IN PROGRESS",
    progress: 42,
    learnedSections: 8,
    totalSections: 19,
    image: reactImg,
    actionIcon: gameIcon,
    progressClass: "second",
  },
  {
    id: 8,
    courseId: "CRS-1008",
    title: "Database Design Basics",
    instructor: "Priya Raman",
    rating: "鈽?4.7",
    reviews: "(640 reviews)",
    status: "IN PROGRESS",
    progress: 55,
    learnedSections: 10,
    totalSections: 18,
    image: pythonImg,
    actionIcon: gameIcon,
  },
  {
    id: 9,
    courseId: "CRS-1009",
    title: "Design Thinking Workshop",
    instructor: "Olivia Bennett",
    rating: "鈽?4.9",
    reviews: "(920 reviews)",
    status: "COMPLETED",
    progress: 100,
    learnedSections: 14,
    totalSections: 14,
    image: uiuxImg,
    actionIcon: gameIcon,
    badgeClass: "completed",
    progressClass: "third",
  },
  {
    id: 10,
    courseId: "CRS-1010",
    title: "Python Automation Lab",
    instructor: "Ethan Brooks",
    rating: "鈽?4.6",
    reviews: "(780 reviews)",
    status: "IN PROGRESS",
    progress: 28,
    learnedSections: 5,
    totalSections: 18,
    image: pythonImg,
    actionIcon: gameIcon,
    progressClass: "second",
  },
  {
    id: 11,
    courseId: "CRS-1011",
    title: "React State Management",
    instructor: "Sophia Lee",
    rating: "鈽?4.8",
    reviews: "(2.1k reviews)",
    status: "IN PROGRESS",
    progress: 67,
    learnedSections: 12,
    totalSections: 18,
    image: reactImg,
    actionIcon: gameIcon,
  },
  {
    id: 12,
    courseId: "CRS-1012",
    title: "UX Research Methods",
    instructor: "Lucas White",
    rating: "鈽?4.9",
    reviews: "(560 reviews)",
    status: "COMPLETED",
    progress: 100,
    learnedSections: 12,
    totalSections: 12,
    image: uiuxImg,
    actionIcon: gameIcon,
    badgeClass: "completed",
    progressClass: "third",
  },
];

export const coursesPageMock = {
  summary: "You have 4 courses in progress this week.",
  filters: ["All", "In Progress", "Completed"],
  courses: coursesMock,
  categories: [
    {
      id: 1,
      title: "Development",
      count: 12,
      icon: devIcon,
    },
    {
      id: 2,
      title: "Design",
      count: 8,
      icon: designIcon,
    },
    {
      id: 3,
      title: "Data Science",
      count: 5,
      icon: dataIcon,
    },
  ],
  goal: {
    label: "WEEKLY GOAL",
    title: "Finish 5 lessons",
    progress: "4/5",
    icon: goalImg,
  },
};
